dataloading:
  path: data/Scannet
  scene: ['scene0418_00']
  random_ref_interval: [1,3,5]
training:
  # Path
  out_dir:  out/Scannet/scene0418_00
  load_dir:  out/Scannet/scene0418_00/models/weights/model.pt
  # Resolution
  original_resolution: [484, 648]
  resolution: [484, 648]
  vis_resolution: [121, 162]
  # Loss weight
  eikonal_weight: [0.1, 0.1]
  sdf_weight: [0.1, 1.0]
  flow_rgb_weight: [7.5,7.5]
  rgb_weight: [1.0,1.0]
  edge_aware_smoothness_weight: [1.0, 1.0]
  smoothness_weight: [0.001, 0.001]
  sdf_consistency_weight: [0.0, 1.0]
  # Sampling points
  patch_size: 4
  n_training_points: 1024
  # Loss annealing
  end_sdf_weight_increase_iteration: 10000
  end_consistency_weight_increase_iteration: 100000
  sdf_consistency_enable_pose_grad: True
  end_smooth_epoch: 201
  # Coarse-to-fine training
  coarse_to_fine_scheduler: {4: [0,201], 2: [200,401], 1: [401, 100000000000]}
  # Stage 2 parameter
  start_query_world_epoch: 1481
  freeze_camera_pose_period: 100000000000000
  # Lr scheduler
  scheduling_epoch: 10000
  scheduling_start: 2500
  # Others
  seed: 2708
  gpu_ids: [0]
  do_refine_pose: False
extract_images:
  resolution: [484, 648]
rendering:
  depth_range: [0.01, 3.0]
neus_variance_network:
  init_val: 0.2

