dataloading:
  path: data/Co3D
  scene: ['plant']
  random_ref_interval: [1,2,3]
training:
  # Path , 
  out_dir:  out/Co3D/plant
  load_dir:  out/Co3D/plant/models/weights/model.pt
  # Resolution
  original_resolution: [1895, 1065]
  resolution: [1895, 1065]
  vis_resolution: [236, 134]
  # Loss weight
  eikonal_weight: [0.1, 0.1]
  sdf_weight: [0.1, 0.1]
  flow_rgb_weight: [7.5,7.5]
  rgb_weight: [1.0,1.0]
  edge_aware_smoothness_weight: [1.0, 0.0]
  smoothness_weight: [0.0001, 0.000]
  sdf_consistency_weight: [0.0, 10.0]
  # Sampling points
  patch_size: 4
  n_training_points: 1024
  # Loss annealing
  end_sdf_weight_increase_iteration: -1
  end_consistency_weight_increase_iteration: 400000
  sdf_consistency_enable_pose_grad: True
  end_smooth_epoch: 201
  # Coarse-to-fine training
  coarse_to_fine_scheduler: {8: [0,201], 2: [200,401], 1: [401, 100000000000]} # dict of {scale: epoch_interval}
  # Stage 2 parameter
  start_query_world_epoch: 5001
  freeze_camera_pose_period: 100000000000000
  # Lr scheduler
  scheduling_epoch: 10000
  scheduling_start: 6001
  # Others
  seed: 678
  gpu_ids: [0]
  # Case specific
extract_images:
  resolution: [1895, 1065]
rendering:
  depth_range: [0.01, 5.0]
neus_variance_network:
  init_val: 0.3

