dataloading:
  path: data/Co3D
  scene: ['skateboard']
  random_ref_interval: [1,2,3]
training:
  # Path , 
  out_dir:  out/Co3D/skateboard
  load_dir:  out/Co3D/skateboard/models/weights/model.pt
  # Resolution
  original_resolution: [717, 1275]
  resolution: [717, 1275]
  vis_resolution: [89, 158]
  # Loss weight
  eikonal_weight: [0.1, 0.1]
  sdf_weight: [0.1, 0.1]
  flow_rgb_weight: [7.5,7.5]
  rgb_weight: [0.33333, 0.33333]
  edge_aware_smoothness_weight: [1.0, 0.0]
  smoothness_weight: [0.0001, 0.000]
  sdf_consistency_weight: [0.0, 1.0]
  # Sampling points
  patch_size: 4
  n_training_points: 1024
  # Loss annealing
  end_sdf_weight_increase_iteration: -1
  end_consistency_weight_increase_iteration: 100000
  sdf_consistency_enable_pose_grad: True
  end_smooth_epoch: 2001
  # Coarse-to-fine training
  coarse_to_fine_scheduler: {8: [0,201], 2: [200,401], 1: [401, 100000000000]} # dict of {scale: epoch_interval}
  # Stage 2 parameter
  start_query_world_epoch: 2001
  freeze_camera_pose_period: 100000000000000
  # Lr scheduler
  scheduling_start: 3001
  # Others
  seed: 678
  gpu_ids: [0]
  # Lr drop stage 1
  lr_drop_half_epoch: [1001, 1501] 
extract_images:
  resolution: [717, 1275]
rendering:
  depth_range: [0.01, 5.0]
neus_variance_network:
  init_val: 0.3

